meta_product_name: "COSMOS"
meta_title: "COSMOS - Let The World See Your Shinning Art"
meta_description: "COSMOS connect artists all over the world for one and only one thing, their arts. Nothing more, to be support or connected with interesting peoples"
meta_image: "cosmos-logo.png"
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
